#!/bin/sh

VERSION=1.5.0

echo "Packing lowlands-$VERSION.tar.gz"

tar -zcvf lowlands-$VERSION.tar.gz backups/area_current.tar.gz backups/clans.tar.gz backups/data.tar.gz backups/doc.tar.gz backups/scripts.tar.gz backups/src.tar.gz backups/castles.tar.gz player/l/o/Lola install README
