#!/bin/bash
echo -n "un-installing lola.."
rm -R area_current >/dev/null 2>/dev/null
rm -R backups >/dev/null 2>/dev/null
echo -n "."
rm -R bin >/dev/null 2>/dev/null
rm -R clans/ >/dev/null 2>/dev/null
echo -n "."
rm -R doc >/dev/null 2>/dev/null
rm -R log >/dev/null 2>/dev/null
echo -n "."
rm -R player >/dev/null 2>/dev/null
rm -R scripts /dev/null 2>/dev/null
echo -n "."
rm -R src >/dev/null 2>/dev/null
rm -R tmp >/dev/null 2>/dev/null
echo -n "."
rm backup compile down lola.csh install mkpackage startup >/dev/null 2>/dev/null
rm -f lola.pid script.pid un-install
echo done.
 